### ISSUE TITLE
代理加速地址链接失效了

### ISSUE THREAD

**Issue by PorkBoneSoup** [entr0pia/SwitchyOmega-Whitelist#3]
您好，最近更新情景模式的时候，白名单的链接地址失效了，更新不了，还有什么可以代替的链接吗？？

**Comment by PorkBoneSoup** [comment]
原因已找出，是网络代理导致的问题

**Comment by entr0pia** [comment]
不, 它确实被墙了
![image](https://github.com/entr0pia/SwitchyOmega-Whitelist/assets/30486766/55658623-8143-4602-81cf-ba39cca06098)
