### ISSUE TITLE
自动切换模式延迟大

### ISSUE THREAD

**Issue by EVA-JianJun** [entr0pia/SwitchyOmega-Whitelist#5]
# 自动切换模式延迟大
## 环境
SwitchyOmega
Switchy 
规则列表规则: 直接连接 
默认情景模式: 代理
win10
Edge

## 症状
每次打开浏览器打开网站都得等 5 到 8 秒不等才能打开网站, 下次再次打开会快些, 重启浏览器症状依旧
直接全走代理会快很多

## 推测
推测因为是白名单, 需要判断比较多, 每次打开所有白名单都得判断一次
使用黑名单规则快很多
好像也没啥解决办法, 毕竟这里是白名单

有 SwitchyOmega 的替代品吗?

**Comment by DiaoWang** [comment]
同样的问题，所以又换回GFWList了。另外是否有人解答下switchy和autoproxy的区别？就只是规则写法不一样么？

**Comment by entr0pia** [comment]
> # 自动切换模式延迟大
> ## 环境
> SwitchyOmega Switchy 规则列表规则: 直接连接 默认情景模式: 代理 win10 Edge
> 
> ## 症状
> 每次打开浏览器打开网站都得等 5 到 8 秒不等才能打开网站, 下次再次打开会快些, 重启浏览器症状依旧 直接全走代理会快很多
> 
> ## 推测
> 推测因为是白名单, 需要判断比较多, 每次打开所有白名单都得判断一次 使用黑名单规则快很多 好像也没啥解决办法, 毕竟这里是白名单
> 
> 有 SwitchyOmega 的替代品吗?

有替代，https://github.com/salarcode/SmartProxy。但年初的时候试用了一下，用起来不方便。最近更新的版本没有尝试
